import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';

import { Agent } from '../../src/core/agent.js';
import { extractSiteTool } from '../../src/tools/extract-site.js';
import type { ILLMProvider } from '../../src/providers/llm-provider.js';
import { createDefaultRegistry } from '../../src/tools/index.js';
import type { ProviderResult, ResolvedConfig } from '../../src/types/index.js';

class CannedProvider implements ILLMProvider {
  private idx = 0;
  constructor(private readonly script: string[]) {}
  async generate(): Promise<ProviderResult> {
    const text = this.script[this.idx] ?? '{"step":"OUTPUT","content":"done"}';
    this.idx += 1;
    return { text, modelUsed: 'mock', latencyMs: 1 };
  }
}

const config: ResolvedConfig = {
  projectId: 'p',
  clientEmail: 'svc@p.iam.gserviceaccount.com',
  privateKey: 'k',
  location: 'global',
  primaryModel: 'mock',
  fallbackModels: [],
  budgetMs: 60_000,
  version: '0.0.0-test',
};

let dir: string;
const ORIGINAL_CWD = process.cwd();

beforeEach(() => {
  dir = mkdtempSync(join(tmpdir(), 'ditto-clone-'));
  process.chdir(dir);
});

afterEach(() => {
  process.chdir(ORIGINAL_CWD);
  rmSync(dir, { recursive: true, force: true });
  vi.restoreAllMocks();
});

describe('Universal clone flow', () => {
  it('drives extractSite -> writeFile x3 -> openInBrowser -> OUTPUT and writes files', async () => {
    const fixturePath = join(dir, 'fake-site.html');
    writeFileSync(
      fixturePath,
      `<!doctype html><html><head><title>Demo</title></head>
       <body><header><nav><a href="/">Home</a></nav></header>
       <main><section class="hero"><h1>Welcome</h1></section></main>
       <footer><h4>Product</h4><ul><li><a>Features</a></li></ul></footer></body></html>`,
    );

    vi.spyOn(extractSiteTool, 'execute').mockResolvedValue({
      url: 'https://demo.example/',
      host: 'demo.example',
      slug: 'demo-example',
      title: 'Demo',
      palette: ['#0EA5E9'],
      fonts: ['Inter'],
      headings: [{ level: 1, text: 'Welcome' }],
      ctas: [{ label: 'Get Started' }],
      navLinks: [{ label: 'Home', href: '/' }],
      footerColumns: [{ title: 'Product', items: ['Features'] }],
      socialLinks: [],
      sectionsDetected: ['header', 'hero', 'footer'],
      rawHtmlLengthBytes: 200,
      isLikelyJsApp: false,
    });

    const provider = new CannedProvider([
      JSON.stringify({ step: 'START', content: 'clone demo.example' }),
      JSON.stringify({
        step: 'TOOL',
        tool_name: 'extractSite',
        tool_args: 'https://demo.example/',
      }),
      JSON.stringify({ step: 'THINK', content: 'I have the brief; writing files' }),
      JSON.stringify({
        step: 'TOOL',
        tool_name: 'writeFile',
        tool_args: {
          path: 'output/demo-example/index.html',
          contents:
            '<!-- Educational clone of demo.example. Generated by Ditto. Not affiliated. -->\n<html><body><h1>Welcome</h1></body></html>\n',
        },
      }),
      JSON.stringify({
        step: 'TOOL',
        tool_name: 'writeFile',
        tool_args: {
          path: 'output/demo-example/styles.css',
          contents: 'body { font-family: Inter, sans-serif; }\n',
        },
      }),
      JSON.stringify({
        step: 'TOOL',
        tool_name: 'writeFile',
        tool_args: {
          path: 'output/demo-example/script.js',
          contents: 'document.addEventListener("DOMContentLoaded", () => {});\n',
        },
      }),
      JSON.stringify({
        step: 'TOOL',
        tool_name: 'openInBrowser',
        tool_args: 'output/demo-example/index.html',
      }),
      JSON.stringify({
        step: 'OUTPUT',
        content: 'Cloned demo.example into output/demo-example/.',
      }),
    ]);

    const registry = createDefaultRegistry();
    const agent = new Agent({ provider, registry, systemPrompt: 'SYSTEM', config });

    const out = await agent.runTurn('Clone https://demo.example/');
    expect(out).toBe('Cloned demo.example into output/demo-example/.');

    const html = readFileSync(join(dir, 'output/demo-example/index.html'), 'utf8');
    expect(html).toContain('Educational clone of demo.example');
    expect(html).toContain('<h1>Welcome</h1>');

    const css = readFileSync(join(dir, 'output/demo-example/styles.css'), 'utf8');
    expect(css).toContain('Inter');

    const js = readFileSync(join(dir, 'output/demo-example/script.js'), 'utf8');
    expect(js).toContain('DOMContentLoaded');
  });
});
